### PR TITLE
Java 8 compatibility

### PR DESCRIPTION
**Pull request by zherebjatjew**
Checkstyle upgraded to 6.4.1

### CODE REVIEW

**Comment by jshiell** [comment]
Thanks, however I can't merge this until at the very least IDEA 14.1 is released, as IDEA currently uses Java 6 on OS X.

**Comment by jshiell** [comment]
And now I'm at work I see my RC2 has updated to what appears to be release :smile: Once the public download is up and I've had a look at #84 I'll get this merged. Many thanks!

**Comment by zherebjatjew** [comment]
Fortunatelly we do not use macs, so using custom build is ok for now. Thank
you for the reply.
24.03.2015 15:26 пользователь "James Shiell" <notifications@github.com>
написал:

**Comment by jshiell** [comment]
Looks like this will be delayed further, as JetBrains have released 14.1 without the custom JDK8 build on the Mac. Sorry.

**Pull request merged**
