### PR TITLE
Let user choose which version of checkstyle to use

### PR DESCRIPTION
**Pull request by tsjensen**
Finally, here is my PR for #199.
As expected, it turned out quite large, so maybe we want to have a little Skype conversation in order to synchronize.
I would also like to take you up on your offer of support. Maybe you could test it and make sure that everything still works. I already installed it on my PC and it looks good to me, but I'm sure you can test this much more thoroughly, and you are aware of pitfalls that I may have missed.

### CODE REVIEW

**Comment by jshiell** [comment]
Awesome stuff! I'll give it a go this weekend (overseas on business during the week, I fear).

**Comment by jshiell** [comment]
I took the lazy option and just merged it, as I think it's definitely worth striving ahead and getting it working before anything else happens to `master` 😄 

I've just had a quick go, and run into a problem on scans:
```
An error occurred while scanning a file.: Couldn't create Checker from 256a
org.infernus.idea.checkstyle.exception.CheckStylePluginException: Couldn't create Checker from 256a
	at org.infernus.idea.checkstyle.checker.CheckerFactory.checker(CheckerFactory.java:64)
	at org.infernus.idea.checkstyle.checker.ScanFiles.checkFiles(ScanFiles.java:198)
	at org.infernus.idea.checkstyle.checker.ScanFiles.processFilesForModuleInfoAndScan(ScanFiles.java:158)
	at org.infernus.idea.checkstyle.checker.ScanFiles.call(ScanFiles.java:87)
	at org.infernus.idea.checkstyle.checker.ScanFiles.call(ScanFiles.java:39)
	at com.intellij.openapi.application.impl.ApplicationImpl$3.call(ApplicationImpl.java:331)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.infernus.idea.checkstyle.exception.CheckStylePluginException: Could not load configuration
	at org.infernus.idea.checkstyle.checker.CheckerFactory.createChecker(CheckerFactory.java:146)
	at org.infernus.idea.checkstyle.checker.CheckerFactory.getOrCreateCachedChecker(CheckerFactory.java:78)
	at org.infernus.idea.checkstyle.checker.CheckerFactory.checker(CheckerFactory.java:58)
	... 9 more
Caused by: org.infernus.idea.checkstyle.exception.CheckStylePluginException: internal error
	at org.infernus.idea.checkstyle.CheckstyleClassLoader.loadCheckstyleImpl(CheckstyleClassLoader.java:138)
	at org.infernus.idea.checkstyle.CheckstyleProjectService.getCheckstyleInstance(CheckstyleProjectService.java:185)
	at org.infernus.idea.checkstyle.checker.CheckerFactoryWorker.run(CheckerFactoryWorker.java:47)
Caused by: java.lang.ClassNotFoundException: org.infernus.idea.checkstyle.service.CheckstyleActionsImpl
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.infernus.idea.checkstyle.CheckstyleClassLoader.loadCheckstyleImpl(CheckstyleClassLoader.java:135)
	... 2 more
```

Before I investigate further I just wanted to sanity check, in case anything had been further altered in the build process that I've missed.

I built via `./gradlew clean test buildPlugin` and this seems to have generated a valid dist JAR - we've got all the CS JARs in there, and the class above and its siblings are all present in `checkstyle/classes`. Looking at `CheckstyleClassLoader` suggests it should very much be on the classpath. Are you using Windows? Only immediate thought is it's something breaking in the paths (I'm on macOS).

In any case, thought it worth a quick check in case I'm being a blatant idiot. If you can't immediately see anything wrong, I'll dive in anon and see what's gone awry.

On the IDEA side I've just imported directly from the Gradle file - thanks for cleaning up the duplicated project files. However, it has lost information about the module being a plugin (which means the debug plugin targets won't work) - any idea on how to fix this? I've had a go at trying to modify the IML XML in the build file, but have had no luck. Thanks.

**Comment by jshiell** [comment]
Hmm. Definitely not paths. After debugging it looks like the classloader is fine. Curiouser and curiouser. Will keep investigating.

On the IDEA debug profiles - looks like the officially supported way is debugging the Gradle target - there's no support for importing plugin modules that I've found. Shame. Ah well.

**Comment by jshiell** [comment]
This gets weirder - if I run IDEA via the `runIdea` target, it works correctly. If I copy the plugin into my local plugin folder, it blows up with the error above.

Out of time right now, but will return to this either later today or tomorrow. Must be something simple 😄

**Comment by tsjensen** [comment]
Thank you for immediately adopting my stuff! Sorry it didn't work right away. I'll do my best to help you sort it out.
I usually build with `.\gradlew build`, which has the added advantage of running the *xtest* task which checks that the unit tests in `csaccessTest` work against all supported Checkstyle runtimes.
And yes, I am on Windows.
What do you mean by "local plugin folder"? When I installed the plugin for testing, I did so via the IDEA Plugins dialog in Settings ("install plugin from disk"). Once I can reproduce the problem on my machine, we should be able to nail it down quickly.
With the symptoms you describe, it could be the heuristics in CheckstyleClassLoader#getBasePath() which tries to guess the plugin's installation directory from the classpath built by the plugin classloader. This is probably not the best practice, but I found no other way.
Anyway, not being able to find `CheckstyleActionsImpl` must be something simple. Can you give me instructions on how exactly to reproduce the problem?

**Comment by tsjensen** [comment]
If removing the IML caused loss of information about the module being a plugin (which means the debug plugin targets won't work), then we should add it again. I spent a lot of time struggling with the [IDEA gradle plugin](https://docs.gradle.org/3.2.1/userguide/idea_plugin.html) to get to flag the `csaccessTest` sources as test sources, to no avail. The Gradle idea plugin is seriously out of date and cannot currently be used to to that. So we have *two* reasons to add back the IML.

**Comment by tsjensen** [comment]
FYI, I added `org.infernus.idea.checkstyle.util.Objects#getClassPath()` which may help printing out the classpath generated in your case.

**Comment by jshiell** [comment]
Got it - spaces and URL encoding. Under macOS the plugin location for the IDE is under `~/Library/Application Support/IntelliJIdea2016.3`, and hence we get double encoding:
```
basePath = /Users/jshiell/Library/Application%20Support/IntelliJIdea2016.3/CheckStyle-IDEA
basePath.toURL() = file:/Users/jshiell/Library/Application%2520Support/IntelliJIdea2016.3/CheckStyle-IDEA/checkstyle/classes 
```
When we run via `runIdea` though we use a sandbox directory without spaces - hence it works correctly.

I've fixed it by adding a URL decode on the path, and everything now seems to be a lot happier. Initial tests look great - thank you! I'll continue to thrash it over the coming days as it'd be great to get this out as soon as possible.

**Comment by tsjensen** [comment]
Good job figuring this out so quickly! :+1:

**Comment by jshiell** [comment]
The only other thing I found was a NPE under certain circumstances where the module wasn't available. Other than that, it's been flawless. I've just released it as 5.0.0.

Thanks again for all your work on this!

**Pull request merged**
