### PR TITLE
Unlock libs

### PR DESCRIPTION
**Pull request by tsjensen**
Here's my PR for #263. It resolves the test case given in the issue.

I basically introduced a new option called "Copy libraries from project directory" which copies all libraries on the classpath that reside under the project directory into a temp dir and uses them from there.

Copy libraries from project directory option

This behavior is now default on Windows.
The temporary copies are updated when the timestamp or size of the library changes.
You will have to restart IDEA when the option is changed, because locks once acquired are only grudgingly released.
This whole thing affects the "loader of checked code", which uses the module classpath. The classloader for Checkstyle is not affected as long as people don't do crazy stuff with their third-party addons. So I changed nothing on the latter.
This change can potentially have a great impact, which is hard to foresee. I made some provisions for corner cases like crazy classpath content, projects with the same name, long path names etc., but this is hard to anticipate completely, so we'll have to keep an eye out for any problems this might cause. Please do some exploratory testing, too. 🍺 Thanks!

I also included a small fix where some test cases no longer worked when run from IDEA due to the new Gradle version.

P.S. One day we need to resync on the import formatter settings. Sorry for messing them up again ...

### CODE REVIEW

**Comment by tsjensen** [comment]
Dang, it seems one of my new test cases is failing on Linux, and I can't test on Linux. 😠 
I'll try getting a better error message on the weekend, or Monday at the latest, and use Travis to resolve this. It seems to be something really simple. Sorry about that.

**Comment by tsjensen** [comment]
Ok, so it's `"a_long_folder/path_more_than_50_characters/in_total"` being hashed to a different value. I'm guessing the slashes ... hold on.

**Comment by jshiell** [comment]
Awesome stuff, as always - thank you! I'll have a bit of a bash with it under OS X before releasing.

> P.S. One day we need to resync on the import formatter settings. Sorry for messing them up again ...

I'd much rather have inconsistent style and solve the problem. Worst come to worst, there's always `reformat code` in IDEA 😄

**Comment by tsjensen** [comment]
@jshiell Btw, your last commit for the release didn't make it onto `master`. Noticed this when rebasing.

**Comment by jshiell** [comment]
Whoops - sorry, pushed!

**Pull request merged**
