### PR TITLE
[WIP] adding CustomOrderImporter

### PR DESCRIPTION
**Pull request by mqzry**
See title.

### CODE REVIEW

**Comment by jshiell** [comment]
Thanks for the contribution. I presume this resolves #362?

**Comment by mqzry** [comment]
Yes that is the goal. What is your plan for the gazillion other modules that do not have an importer yet?

**Comment by jshiell** [comment]
There is no plan. The importer was a contribution - I've no interest myself in expanding it, but am happy to merge contributions that do so.

**Comment by mqzry** [comment]
Can you reopen this somehow? It is a work in progress, need to implement a some more.

**Comment by jshiell** [comment]
GitHub UI doesn't seem to give me the option. I wasn't expecting a incomplete pull request. I'd expect you'd need to push more commits to the appropriate branch and that might allow it (as there would be something new to pull). If not, I can try a revert.

**Comment by mqzry** [comment]
I'll just do the work and make a new PR.

**Pull request merged**
