### PR TITLE
#621: Allow additional bundled configs

### PR DESCRIPTION
**Pull request by rhierlmeier**

### CODE REVIEW

**Comment by jshiell** [comment]
Thanks very much - I'll try have a look at this when I'm back from business travel in just over a week 🤞

**Comment by rhierlmeier** [comment]
Great, 
what I have not done is providing a API Maven artifact for the provider interface that has to be implemented by the additional bundle configs.

**Comment by jshiell** [comment]
Thanks, this looks simple and effective. I'll get it merged so you can use it, and the Maven niceties can come later.

**Comment by rhierlmeier** [comment]
Thank you for merging this PR. When is the next release planned?

Do we need some kind of documentation for this feature?

**Comment by jshiell** [comment]
It was included in the release made on the same day. Documentation would certainly be nice as well - I haven't made an effort there as yet!

**Comment by jshiell** [comment]
I added some basic instructions based on your comments in #621 in [3925513](https://github.com/jshiell/checkstyle-idea/commit/392551343b6b8320a5ae55b57cc14e8d54f209e5)

**Pull request merged**
