### PR TITLE
Issue #522: LocalizedMessage Class renamed to Violation in checkstyle

### LINKED ISSUE #522: LocalizedMessage Class renamed to Violation in checkstyle
From: https://github.com/checkstyle/checkstyle/pull/9761#issuecomment-813397729

In a recent change `LocalizedMessage` class was renamed to `Violation` in checkstyle and the change has to be reflected here as well for successful passing of the tests.

### PR DESCRIPTION
**Pull request by AkMo3**
Closes #522

### CODE REVIEW

**Comment by tsjensen** [comment]
If this a change that depends on / is caused by the Checkstyle version, you will probably need to address it reflectively, because we support multiple Checkstyle versions at once.

**Comment by AkMo3** [comment]
> If this a change that depends on / is caused by the Checkstyle version, you will probably need to address it reflectively, because we support multiple Checkstyle versions at once.

Can you please explain in a bit of detail what needs to be done, and how can be done?

**Comment by tsjensen** [comment]
Well, the purpose of the *csaccessTest* source set is to run its tests against all supported Checkstyle runtimes. So in some invocations, you'll have a `Violation` class, in others a `LocalizedMessage`. Using either of these types will cause a ClassNotFound exception in some tests.

Therefore, your code must be coded using [reflection](https://www.oracle.com/technical-resources/articles/java/javareflection.html) so that it does not require the concrete type.

**Comment by AkMo3** [comment]
> Well, the purpose of the _csaccessTest_ source set is to run its tests against all supported Checkstyle runtimes. So in some invocations, you'll have a `Violation` class, in others a `LocalizedMessage`. Using either of these types will cause a ClassNotFound exception in some tests.
> 
> Therefore, your code must be coded using [reflection](https://www.oracle.com/technical-resources/articles/java/javareflection.html) so that it does not require the concrete type.

Thanks for the detailed explanation. Please check now.

**Comment by tsjensen** [comment]
Right, this should work! 👍

**Comment by jshiell** [comment]
Thanks muchly - I’m having a busy few days at present, but will attempt to get this merged ASAP!

**Pull request merged**
